version: "3"
services:
  php_fpm:
    build: containers/php_fpm
    image: broken-link-checker_php_fpm
    environment:
      - COMPOSER_CACHE_DIR=/var/app/var/cache/composer
      - COMPOSER_ALLOW_SUPERUSER=1
    networks:
      default_network:
    volumes:
      - .:/var/app
#  php_fpm_debug:
#    build: containers/php_fpm_debug
#    environment:
#      - COMPOSER_CACHE_DIR=/var/app/var/cache/composer
#      - COMPOSER_ALLOW_SUPERUSER=1
#    depends_on:
#      - php_fpm
#    networks:
#      default_network:
#    volumes:
#      - .:/var/app
networks:
  default_network: